// Mattarello: fresh pasta bar. Menu data, illustrations and builder options.

// Line illustrations (64×64, drawn with currentColor). The paths are reused
// inside the bowl of the builder, so they are kept separate from the wrapper.
const ICON_PATHS = {
  spaghetti: '<path d="M14 34c0-10 8-18 18-18s18 8 18 18-8 16-18 16-14-6-14-14 6-12 14-12 10 4 10 10-4 8-8 8-6-2-6-6"/><path d="M45 21l8-9M48 25l9-7"/>',
  rigatoni: '<g transform="rotate(-24 32 32)"><ellipse cx="18" cy="32" rx="6" ry="11"/><path d="M18 21h26c4 0 6 5 6 11s-2 11-6 11H18"/><path d="M26 21.5v21M33 21.5v21M40 21.5v21"/></g>',
  pappardelle: '<path d="M8 20c8-6 14 6 24 0s16 6 24 0v9c-8 6-14-6-24 0s-16-6-24 0z"/><path d="M8 37c8-6 14 6 24 0s16 6 24 0v9c-8 6-14-6-24 0s-16-6-24 0z"/>',
  orecchiette: '<ellipse cx="32" cy="33" rx="20" ry="15"/><ellipse cx="32" cy="31" rx="10" ry="6.5"/><path d="M20 41c7 4 17 4 24 0"/>',
  gnocchi: '<path d="M14 27c0-6 8-8 18-8s18 2 18 8v10c0 6-8 8-18 8s-18-2-18-8z"/><path d="M22 20.5v23.5M29 19.2v26.6M36 19.2v26.6M43 20.5v23.5"/>',
  fusilli: '<path d="M10 40c4-10 8-10 10 0s6 10 10 0 6-10 10 0 6 10 10 0 4-10 6-6"/><path d="M10 28c4-10 8-10 10 0s6 10 10 0 6-10 10 0 6 10 10 0 4-10 6-6" opacity=".55"/>',
  tortellini: '<path d="M16 38c-4-12 6-24 16-22s18 12 14 22"/><path d="M16 38c7 7 23 7 30 0"/><path d="M25 36c0-6 3-10 7-10s7 4 6 10"/>',
  ravioli: '<rect x="13" y="13" width="38" height="38" rx="3" stroke-dasharray="3.5 3.5"/><circle cx="32" cy="32" r="11"/>',
  lasagna: '<path d="M10 26h44v22H10z"/><path d="M10 33.5h44M10 41h44"/><path d="M10 26c4-4 8 2 12-2s8 2 12-2 8 2 12-2 6 2 8 0"/>',
  bucatini: '<path d="M10 22c10 0 14 20 24 20s12-14 20-14"/><path d="M10 30c10 0 14 20 24 20s12-14 20-14"/><circle cx="54" cy="28" r="2.4"/><circle cx="54" cy="36" r="2.4"/>',
  burrata: '<circle cx="32" cy="36" r="16"/><path d="M24 22c2-6 14-6 16 0"/><path d="M27 21c-1-4 2-7 5-7s6 3 5 7"/><path d="M24 38c3 4 9 5 14 2"/>',
  focaccia: '<rect x="10" y="18" width="44" height="30" rx="8"/><circle cx="21" cy="28" r="2"/><circle cx="33" cy="34" r="2"/><circle cx="44" cy="26" r="2"/><circle cx="25" cy="40" r="2"/><circle cx="44" cy="40" r="2"/>',
  arancini: '<path d="M32 12c10 8 16 18 16 26a16 16 0 0 1-32 0c0-8 6-18 16-26z"/><path d="M24 34l3 3M36 30l3 3M30 44l3 3M40 41l2 2M22 44l2 2"/>',
  artichoke: '<path d="M32 52c-12 0-18-10-18-20 6 2 10 6 12 10-2-10 0-18 6-26 6 8 8 16 6 26 2-4 6-8 12-10 0 10-6 20-18 20z"/><path d="M32 52v6"/>',
  leaf: '<path d="M14 50C14 26 28 14 52 12c0 24-14 38-38 38z"/><path d="M14 50 40 24"/>',
  wine: '<path d="M21 10h22c0 14-4 22-11 22s-11-8-11-22z"/><path d="M32 32v18M23 52h18"/><path d="M22 19h20"/>',
  bottle: '<path d="M28 8h8v12c5 3 7 7 7 12v20a4 4 0 0 1-4 4H25a4 4 0 0 1-4-4V32c0-5 2-9 7-12z"/><path d="M21 36h22v10H21"/>',
  tiramisu: '<path d="M12 28h40v20H12z"/><path d="M12 35h40M12 42h40"/><path d="M12 28c4-3 8 2 12-1s8 2 12-1 8 2 12-1 4 2 4 1"/>',
  cannoli: '<path d="M14 40 42 16a8 8 0 0 1 10 10L24 50a8 8 0 0 1-10-10z"/><path d="M12 42c-3 3 0 8 4 6M50 14c3-3 8 0 6 4"/><path d="M30 30l4 4"/>',
  pannacotta: '<path d="M18 46h28l-4-22H22z"/><path d="M22 24c3 4 17 4 20 0"/><path d="M14 50h36"/><path d="M28 30c2 4 6 4 8 0"/>',
  gelato: '<path d="M22 32l10 24 10-24"/><circle cx="26" cy="24" r="8"/><circle cx="38" cy="24" r="8"/><path d="M26 40h12"/>',
  espresso: '<path d="M14 26h30v10a14 14 0 0 1-28 0z"/><path d="M44 29h4a5 5 0 0 1 0 10h-6"/><path d="M10 52h40"/><path d="M24 12c-2 4 2 6 0 10M32 12c-2 4 2 6 0 10"/>',
  lemon: '<ellipse cx="32" cy="34" rx="19" ry="13" transform="rotate(-25 32 34)"/><path d="M47 19l5-5"/><path d="M24 36c4 3 10 1 13-4"/>',
  water: '<path d="M26 8h12v6l4 6v34a4 4 0 0 1-4 4H26a4 4 0 0 1-4-4V20l4-6z"/><path d="M22 30h20M22 44h20"/>',
};
const ICONS = Object.fromEntries(Object.entries(ICON_PATHS).map(([k, p]) => [k,
  `<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round">${p}</svg>`]));

const PORTION = {
  id: 'portion', name: 'Portion', type: 'single', required: true,
  choices: [
    { id: 'primo', name: 'Primo (regular)', hidden: true },
    { id: 'mezza', name: 'Mezza porzione (half)', price: -3 },
    { id: 'abbondante', name: 'Abbondante (generous)', price: 4 },
  ],
};
const GF = {
  id: 'dough', name: 'Pasta', type: 'single', required: true,
  choices: [
    { id: 'house', name: 'Fresh house pasta', hidden: true },
    { id: 'gf', name: 'Gluten-free pasta', price: 2 },
  ],
};
const TOP = {
  id: 'top', name: 'On top', type: 'multi', max: 3,
  choices: [
    { id: 'parm', name: 'Extra Parmigiano 24 mesi', price: 1.5 },
    { id: 'burrata', name: 'Half a burrata', price: 4 },
    { id: 'chili', name: 'Calabrian chili oil', price: 1 },
    { id: 'crumbs', name: 'Toasted garlic breadcrumbs', price: 1 },
  ],
};
const GLASS = (glass, bottle) => ({
  id: 'serve', name: 'Serve', type: 'single', required: true,
  choices: [
    { id: 'glass', name: 'Glass (150 ml)' },
    { id: 'carafe', name: 'Carafe (500 ml)', price: +(glass * 2.6 - glass).toFixed(2) },
    { id: 'bottle', name: 'Bottle (750 ml)', price: bottle - glass },
  ],
});

window.RESTAURANT = {
  id: 'mattarello',
  name: 'Mattarello',
  kicker: 'PASTA FRESCA · ROMA',
  tagline: 'Rolled by hand at seven. On your plate by noon.',
  taglineHtml: 'Rolled by hand at <em>seven</em>. On your plate by noon.',
  intro: 'Every shape is made in our window each morning from Senatore Cappelli semolina and free-range yolks. Fresh pasta cooks in three minutes, so everything is made the moment you order.',
  facts: ['Pasta rolled today: 14 kg', 'Pranzo 12:00–15:00 · Cena 19:00–23:00', 'Via dei Serpenti 41, Monti'],
  address: 'Via dei Serpenti 41, 00184 Roma',
  hours: 'Tue–Sun · Lunch 12:00–15:00 · Dinner 19:00–23:00 · Closed Monday',
  phone: '+39 06 5550 1923',
  allergyNote: 'Our pasta contains egg and gluten unless marked. Tell us about any allergy.',
  searchHint: 'carbonara, ragù, tiramisù…',
  notePlaceholder: 'Allergies, al dente please, sauce light…',
  currency: 'EUR',
  locale: 'it-IT',
  taxRate: 0,
  taxNote: 'Prices include VAT (IVA).',
  orderPrefix: 'M',
  cookingStep: 'In the pot',
  cover: { label: 'Coperto (bread & service)', price: 2.5 },
  courseTiming: ['Antipasti first, then pasta', 'Everything together', 'Pasta first, then the rest'],
  modes: { dinein: true, pickup: true, delivery: true },
  prepTime: { pickup: '20–25 min', delivery: '35–50 min' },
  deliveryFee: 2.9,
  freeDeliveryOver: 35,
  minDelivery: 15,
  promos: {
    PRIMO10: { type: 'percent', value: 10, label: '10% off' },
    NONNA5: { type: 'amount', value: 5, label: '5 € off' },
  },
  promoHint: 'Try PRIMO10',
  orderEndpoint: null,
  pairTitle: 'The sommelier suggests',
  upsellTitle: 'To finish the meal',
  upsell: ['tiramisu', 'focaccia', 'espresso', 'limoncello'],
  icons: ICONS,
  defaultSkin: 'nonna',
  skins: [
    { id: 'nonna', name: 'Da Nonna', about: 'A neighborhood trattoria: red gingham tablecloth, basil green, handwritten menu.', colors: ['#C8102E', '#FFFFFF', '#2F7D32'] },
    { id: 'dolce', name: 'La Dolce Vita', about: 'The Riviera in 1962: Vespa mint, Campari red and a striped beach awning.', colors: ['#8ED1BC', '#E8503F', '#FFFFFF'] },
    { id: 'notte', name: 'Notte', about: 'A candlelit wine bar: dark wood, cream lettering and gold.', colors: ['#120B0A', '#E0AE4C', '#F2E6D4'] },
  ],
  iconPaths: ICON_PATHS,
  tagLabels: { veg: 'Vegetarian', vegan: 'Vegan', gf: 'Gluten-free', spicy: 'Piccante' },

  categories: [
    {
      id: 'antipasti', name: 'Antipasti', kicker: 'Per cominciare · To start',
      items: [
        { id: 'burrata', name: 'Burrata pugliese', price: 11, icon: 'burrata', tags: ['veg', 'gf', 'popular'], pair: 'vermentino',
          desc: 'A whole burrata from Andria, heirloom tomatoes, basil oil and flaky salt.' },
        { id: 'focaccia', name: 'Focaccia della casa', price: 5, icon: 'focaccia', tags: ['vegan'],
          desc: 'Baked twice a day. Rosemary, Ligurian olive oil, sea salt.' },
        { id: 'arancini', name: 'Arancini cacio e pepe (3)', price: 8.5, icon: 'arancini', tags: ['veg'],
          desc: 'Crisp saffron risotto balls with a molten pecorino and black pepper heart.' },
        { id: 'carciofi', name: 'Carciofi alla romana', price: 9, icon: 'artichoke', tags: ['vegan', 'gf'],
          desc: 'Roman artichokes braised with mint, garlic and white wine.', left: 5 },
        { id: 'finocchio', name: 'Insalata di finocchi', price: 8, icon: 'leaf', tags: ['vegan', 'gf'],
          desc: 'Shaved fennel, blood orange, black olives and toasted pine nuts.' },
      ],
    },
    {
      id: 'build', name: 'Build your bowl', kicker: 'Fatta a mano · Made your way', type: 'builder',
      blurb: 'Pick a shape, a sauce and what goes on top. We cook it to order.',
      items: [
        {
          id: 'bowl', name: 'Your pasta bowl', price: 12, icon: 'spaghetti',
          desc: 'Fresh pasta of your choice, cooked to order with your sauce and toppings.',
          options: [
            { id: 'shape', name: 'Pasta shape', type: 'single', required: true, choices: [
              { id: 'spaghetti', name: 'Spaghetti alla chitarra', icon: 'spaghetti', about: 'Square-cut egg strands. Grip creamy sauces.' },
              { id: 'rigatoni', name: 'Rigatoni', icon: 'rigatoni', about: 'Ridged tubes that trap chunky sauce inside.' },
              { id: 'pappardelle', name: 'Pappardelle', icon: 'pappardelle', price: 1, about: 'Wide ribbons, made for slow-cooked ragù.' },
              { id: 'orecchiette', name: 'Orecchiette', icon: 'orecchiette', about: 'Little ears from Puglia. Each one holds a spoon of sauce.' },
              { id: 'gnocchi', name: 'Potato gnocchi', icon: 'gnocchi', price: 1, about: 'Soft potato dumplings, rolled on a wooden paddle.' },
              { id: 'fusilli', name: 'Gluten-free fusilli', icon: 'fusilli', price: 2, gf: true, about: 'Corn and rice spirals. Cooked in a separate pot.' },
            ] },
            { id: 'sauce', name: 'Sauce', type: 'single', required: true, choices: [
              { id: 'pomodoro', name: 'Pomodoro & basil', color: '#D8442B', veg: true, about: 'San Marzano tomatoes, garlic, torn basil.' },
              { id: 'cacio', name: 'Cacio e pepe', color: '#EADCAF', price: 1, veg: true, about: 'Pecorino Romano and toasted Tellicherry pepper.' },
              { id: 'ragu', name: 'Ragù bolognese', color: '#8A3A22', price: 3, about: 'Beef and pork, eight hours on the stove.' },
              { id: 'pesto', name: 'Pesto genovese', color: '#6E9A3A', price: 1.5, veg: true, about: 'Basil, pine nuts, Parmigiano, Ligurian oil.' },
              { id: 'vodka', name: 'Rosa alla vodka', color: '#E58A6A', price: 2, veg: true, about: 'Tomato, cream, a splash of vodka and chili.' },
              { id: 'burro', name: 'Brown butter & sage', color: '#C7913F', price: 1, veg: true, about: 'Nutty butter with crisp sage leaves.' },
              { id: 'aglio', name: 'Aglio, olio e peperoncino', color: '#E2C35A', vegan: true, about: 'Garlic, olive oil and dried chili.' },
            ] },
            { id: 'extras', name: 'Add on top', type: 'multi', max: 3, choices: [
              { id: 'burrata', name: 'Burrata', price: 3.5, about: 'Half a burrata, torn over the top.' },
              { id: 'guanciale', name: 'Crispy guanciale', price: 3, about: 'Cured pork cheek, rendered crisp.' },
              { id: 'salsiccia', name: 'Fennel sausage', price: 3, about: 'Crumbled and browned.' },
              { id: 'pomodorini', name: 'Roasted cherry tomatoes', price: 1.5, about: 'Blistered in the oven.' },
              { id: 'funghi', name: 'Porcini mushrooms', price: 2.5, about: 'Sautéed with parsley.' },
              { id: 'chili', name: 'Calabrian chili', price: 1, about: 'Fruity, medium heat.' },
            ] },
            { id: 'finish', name: 'Finish', type: 'single', required: true, choices: [
              { id: 'parmigiano', name: 'Parmigiano 24 mesi', about: 'Aged two years, nutty and sweet.' },
              { id: 'pecorino', name: 'Pecorino Romano', about: 'Sheep’s milk, salty and sharp.' },
              { id: 'pangrattato', name: 'Toasted breadcrumbs', about: 'The vegan crunch, with lemon zest.' },
              { id: 'none', name: 'Nothing, thanks', about: 'Just pasta and sauce.' },
            ] },
            PORTION,
          ],
        },
      ],
    },
    {
      id: 'classici', name: 'House classics', kicker: 'I classici · Our recipes',
      blurb: 'The plates Rome argues about. Made exactly the way we think they should be.',
      items: [
        { id: 'carbonara', name: 'Spaghetti alla carbonara', price: 15, icon: 'spaghetti', tags: ['popular'], pair: 'frascati',
          desc: 'Guanciale, free-range yolks, Pecorino Romano, black pepper. No cream, ever.', options: [PORTION, GF, TOP] },
        { id: 'cacio', name: 'Tonnarelli cacio e pepe', price: 13, icon: 'spaghetti', tags: ['veg'], pair: 'frascati',
          desc: 'Pecorino and toasted pepper whipped into a glossy sauce with pasta water.', options: [PORTION, GF, TOP] },
        { id: 'ragu', name: 'Pappardelle al ragù', price: 17, icon: 'pappardelle', tags: ['popular'], pair: 'chianti', left: 6,
          desc: 'Wide egg ribbons with our eight-hour beef and pork ragù and Parmigiano.', options: [PORTION, TOP] },
        { id: 'amatriciana', name: 'Bucatini all’amatriciana', price: 15, icon: 'bucatini', tags: ['spicy'], pair: 'montepulciano',
          desc: 'Guanciale, San Marzano tomato, a pinch of chili and Pecorino.', options: [PORTION, GF, TOP] },
        { id: 'vodka', name: 'Rigatoni alla vodka', price: 15, icon: 'rigatoni', tags: ['veg'], pair: 'lambrusco',
          desc: 'Tomato, cream, vodka and Calabrian chili, finished with basil.', options: [PORTION, GF, TOP] },
        { id: 'vongole', name: 'Spaghetti alle vongole', price: 19, icon: 'spaghetti', pair: 'vermentino',
          desc: 'Venus clams, garlic, parsley and a splash of Vermentino.', options: [PORTION, GF] },
        { id: 'orecchiette', name: 'Orecchiette, salsiccia e cime di rapa', price: 16, icon: 'orecchiette', pair: 'montepulciano',
          desc: 'Puglia’s classic: fennel sausage, turnip greens, chili and breadcrumbs.', options: [PORTION, TOP] },
        { id: 'ravioli', name: 'Ravioli ricotta e limone', price: 16, icon: 'ravioli', tags: ['veg', 'new'], pair: 'vermentino',
          desc: 'Sheep’s ricotta and Amalfi lemon parcels in brown butter with sage.', options: [PORTION, TOP] },
        { id: 'gnocchi', name: 'Gnocchi alla sorrentina', price: 14, icon: 'gnocchi', tags: ['veg'], pair: 'lambrusco',
          desc: 'Potato gnocchi baked with tomato, fior di latte and basil.', options: [PORTION, TOP] },
        { id: 'lasagna', name: 'Lasagna verde', price: 17, icon: 'lasagna', tags: ['popular'], pair: 'lambrusco',
          desc: 'Spinach sheets layered with ragù and béchamel. Baked to order, allow 20 minutes.' },
        { id: 'tortellini', name: 'Tortellini in brodo', price: 16, icon: 'tortellini', soldOut: true,
          desc: 'Bologna’s little pork-filled rings in a capon broth. Back on Sunday.' },
      ],
    },
    {
      id: 'dolci', name: 'Dolci', kicker: 'Per finire · Desserts',
      items: [
        { id: 'tiramisu', name: 'Tiramisù', price: 7, icon: 'tiramisu', tags: ['veg', 'popular'], pair: 'espresso',
          desc: 'Savoiardi soaked in espresso, mascarpone cream, bitter cocoa. Made every morning.' },
        { id: 'cannolo', name: 'Cannolo siciliano', price: 5, icon: 'cannoli', tags: ['veg'],
          desc: 'Filled to order with sheep’s ricotta, candied orange and pistachio.' },
        { id: 'pannacotta', name: 'Panna cotta', price: 6, icon: 'pannacotta', tags: ['veg', 'gf'],
          desc: 'Vanilla cream with a warm wild-berry sauce.' },
        { id: 'gelato', name: 'Gelato, two scoops', price: 5, icon: 'gelato', tags: ['veg', 'gf'],
          desc: 'From Fatamorgana down the street.',
          askOptions: true,
          options: [{ id: 'gusti', name: 'Pick 2 flavors', type: 'multi', required: true, max: 2, choices: [
            { id: 'pistacchio', name: 'Pistacchio di Bronte' }, { id: 'nocciola', name: 'Nocciola' },
            { id: 'stracciatella', name: 'Stracciatella' }, { id: 'limone', name: 'Limone (vegan)' }, { id: 'cioccolato', name: 'Cioccolato fondente' },
          ] }] },
      ],
    },
    {
      id: 'bere', name: 'Wine & drinks', kicker: 'Da bere · To drink',
      blurb: 'Wines by the glass, carafe or bottle. Dine-in and pickup only for wine.',
      items: [
        { id: 'frascati', name: 'Frascati Superiore', price: 6, icon: 'wine', pairNote: 'Glass ·', desc: 'Lazio white. Crisp, almond finish. The local choice for carbonara.', options: [GLASS(6, 26)] },
        { id: 'vermentino', name: 'Vermentino di Sardegna', price: 7, icon: 'wine', pairNote: 'Glass ·', desc: 'Saline and citrusy. Lovely with seafood and burrata.', options: [GLASS(7, 30)] },
        { id: 'chianti', name: 'Chianti Classico', price: 8, icon: 'wine', pairNote: 'Glass ·', desc: 'Tuscan Sangiovese. Cherry, herbs, firm tannins.', options: [GLASS(8, 34)] },
        { id: 'montepulciano', name: 'Montepulciano d’Abruzzo', price: 6.5, icon: 'wine', pairNote: 'Glass ·', desc: 'Juicy, dark fruit, soft. Built for tomato and pork.', options: [GLASS(6.5, 27)] },
        { id: 'lambrusco', name: 'Lambrusco di Sorbara', price: 6, icon: 'wine', pairNote: 'Glass ·', desc: 'Dry sparkling red from Modena, served chilled.', options: [GLASS(6, 25)] },
        { id: 'limoncello', name: 'Limoncello', price: 4.5, icon: 'lemon', tags: ['vegan', 'gf'], desc: 'Made in house from Amalfi lemons. Ice cold.' },
        { id: 'espresso', name: 'Espresso', price: 1.8, icon: 'espresso', tags: ['vegan', 'gf'], pairNote: '',
          desc: 'Roasted by Sant’Eustachio.',
          options: [{ id: 'style', name: 'Style', type: 'single', required: true, choices: [
            { id: 'normale', name: 'Normale', hidden: true }, { id: 'macchiato', name: 'Macchiato', price: 0.3 }, { id: 'corretto', name: 'Corretto (with grappa)', price: 1.5 },
          ] }] },
        { id: 'acqua', name: 'Acqua minerale (75 cl)', price: 3, icon: 'water', tags: ['vegan', 'gf'], desc: 'Still or sparkling.',
          options: [{ id: 'type', name: 'Type', type: 'single', required: true, choices: [{ id: 'naturale', name: 'Naturale (still)' }, { id: 'frizzante', name: 'Frizzante (sparkling)' }] }] },
      ],
    },
  ],
};
